name: composer-test

on: [pull_request, push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: 
        cargo build --manifest-path=composer/Cargo.toml --release --verbose
    - name: Run tests
      run: 
        cargo test --manifest-path=composer/Cargo.toml --release --verbose
